version: '3.8'

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./uploads:/app/uploads
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/llama-2-7b
    restart: unless-stopped
    networks:
      - rag-network

  frontend:
    build:
      context: ./services/web-app
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rag-network

networks:
  rag-network:
    driver: bridge 